### PR TITLE
Prefer iTerm2.app/Terminal.app notification icon on macOS

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by frewsxcv** [comment]
I _want_ to use `"terminal"` for the bundle identifier, but it doesn't seem to work for me. When I use this line:

```rust
let bundle = mac_notification_sys::get_bundle_identifier("terminal").unwrap();
```

...here's what happens:

untitled

The notification doesn't slide over from the top right of the screen like it does for the `"safari"` bundle identifier. It _does_ show up in the Notification Center though....

Have any idea why that's happening?

**Comment by messense** [comment]
@frewsxcv Did you set your notification center alert style to None for Terminal.app in Notifications System Preferences or maybe `Do Not Disturb` is on?

Ref: https://support.apple.com/kb/PH25743?locale=en_US

**Comment by frewsxcv** [comment]
screen shot 2017-04-03 at 10 27 58 pm

**Comment by frewsxcv** [comment]
> or maybe `Do Not Disturb` is on?

If 'Do Not Disturb' was on, I wouldn't be getting the `"safari"` bundle notifications.

**Comment by messense** [comment]
It's odd, mine is working.

image

**Comment by messense** [comment]
Oh...When I run it in iTerm2.app using `terminal` identifier it is working, but when I run it in Terminal.app it behaves like yours, only when the Terminal.app window is not in foreground the notification would slide over.

**Comment by frewsxcv** [comment]
Oh that's it. It only displays a notification if the bundle is not currently active. Hmm. Wonder how I should handle this.

**Comment by frewsxcv** [comment]
I want to find a way to _always_ display a notification, even if the app is selected, because the user might be using a different Terminal.app window.

**Comment by messense** [comment]
But when I use `iterm2` identifier and use iTerm2.app to run it and keep iTerm2 window active the notification displays, this is odd...

**Comment by frewsxcv** [comment]
Well, for now, I'm just going to specify Script Editor instead of Safari, I think that's a little less weird:

screen shot 2017-04-03 at 11 22 31 pm

**Comment by frewsxcv** [comment]
https://github.com/frewsxcv/alert-after/commit/49fad0c5d7958eb01ce9beb3e0c4c0a5e4397c46

**Pull request closed without merging**
